### ISSUE TITLE
i got error Failed to login: error status: 401, error message: {"statusCode":401,"message":"Authentication failed"} panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by MHendriF** [ehhramaaa/CapyMeme#1]
![image](https://github.com/user-attachments/assets/12c8f519-bb73-4428-ac48-25daa233759b)

**Comment by ehhramaaa** [comment]
The code hasn't been updated yet, but I will fix it as soon as possible.

**Comment by ehhramaaa** [comment]
The issue has been fixed. And bot has beed updated. You can try running a git pull or re-cloning the repository. Thanks
